esphome:
  name: ir
  friendly_name: ir

esp8266:
  board: nodemcu

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "MlXC/1dFe5RkEIJAvsy9/8jgGkRTM8bSCAZByc/76UE="

ota:
  password: "947d3e133be97fed74fe07993140cb77"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ir Fallback Hotspot"
    password: "EOdxA45acUW4"

captive_portal:
    