esphome:
  name: ir
  friendly_name: IR Blaster

esp8266:
  board: nodemcuv2

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key_ir

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ir Fallback Hotspot"
    password: "brnHGFS0QVkk"

captive_portal:

remote_transmitter:
  pin: D1
  carrier_duty_percent: 50%

switch:
  - platform: template
    name: "Pioneer toggle"
    turn_on_action:
      remote_transmitter.transmit_pioneer:
        rc_code_1: 0xA556
        rc_code_2: 0xA506
        repeat:
          times: 2
  - platform: template
    name: "Sony toggle"
    turn_on_action:
      remote_transmitter.transmit_sony:
        data: 0x123
        nbits: 12


remote_receiver:
    pin: D2
    dump: all