esphome:
  name: ir
  friendly_name: IR Blaster

esp8266:
  board: nodemcuv2

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key_ir

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ir Fallback Hotspot"
    password: "brnHGFS0QVkk"

captive_portal:

remote_transmitter:
  pin: D1
  carrier_duty_percent: 50%

button:
  - platform: template
    name: "Pioneer power"
    on_press:
      remote_transmitter.transmit_pioneer:
        rc_code_1: 0x65A1
        rc_code_2: 0xF5BC
        repeat:
          times: 2
  - platform: template
    name: "Pioneer Line"
    on_press:
      remote_transmitter.transmit_pioneer:
        rc_code_1: 0x65A0
        rc_code_2: 0xF5A4
        repeat:
          times: 2
  - platform: template
    name: "Pioneer Volume Up"
    on_press:
      remote_transmitter.transmit_pioneer:
        rc_code_1: 0x650A
        repeat:
          times: 2
  - platform: template
    name: "Pioneer Volume Down"
    on_press:
      remote_transmitter.transmit_pioneer:
        rc_code_1: 0x650B
        repeat:
          times: 2
  - platform: template
    name: "Pioneer Mute"
    on_press:
      remote_transmitter.transmit_pioneer:
        rc_code_1: 0x651E
        repeat:
          times: 2
  - platform: template
    name: "Sony Power"
    on_press:
      remote_transmitter.transmit_sony:
        data: 0xA90
        nbits: 12
        repeat:
          times: 4

#remote_receiver:
#    pin: 
#      number: D2
#      inverted: True
#    dump: all