esphome:
  name: temphum
  friendly_name: TempHum

esp8266:
  board: nodemcuv2

# Enable logging
logger:

status_led:
  pin: GPIO3
# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key_temphum

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Temphum Fallback Hotspot"
    password: "vwgBt3DfS5V3"

captive_portal:

sensor:
  - platform: dht
    pin: GPIO2
    temperature:
      name: "Bedroom Temperature"
    humidity:
      name: "Bedroom Humidity"
    update_interval: 30s    
    model: DHT11